#!/usr/bin/env bash
# Generated by esper:init. Commands are project-specific and static.
FAILED=0

# No lint or typecheck commands configured for this project.
# Add commands here if lint/typecheck are added in future.

if [ $FAILED -ne 0 ]; then
  echo ""
  echo "esper: verification failed — fix the errors above before continuing."
fi

exit 0
